name: Mastory Content Action
description: Propagates changes to your repository so they become directly available in Mastory.

inputs:
  scope:
    description: Your content contributor scope (by default, your GitHub user or organization name). Check your profile page on mastory.io if you are unsure what your scope name is.
    required: false
    default: mastoryberlin

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: tj-actions/changed-files@v45
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.scope }}
      shell: bash
      env:
        ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}