name: Mastory Content Action
description: Propagates changes to your repository so they become directly available in Mastory.

inputs:
  scope:
    description: Your content contributor scope (by default, your GitHub user or organization name). Check your profile page on mastory.io if you are unsure what your scope name is.
    required: false
    default: ${{ github.repository_owner_id }}
  api_key:
    description: Your Mastory API key.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: changes
      uses: tj-actions/changed-files@v45
    - shell: bash
      env:
        URL_BASE: https://app.mastory.io/api/content
      run: |
        echo "Your scope is ${{ inputs.scope }}"

        echo "Processing added files"
        for file in ${{ steps.changes.outputs.added_files }}; do
          echo "- adding $file ..."
          echo -n "  "
          curl -s -X PUT $URL_BASE/${{ inputs.scope }}/$file -H "x-mastory-api-key: ${{ inputs.api_key }}" --upload-file "$file"
        done

        echo "Processing modified files"
        for file in ${{ steps.changes.outputs.modified_files }}; do
          echo "- updating $file ..."
          echo -n "  "
          curl -s -X PATCH $URL_BASE/${{ inputs.scope }}/$file -H "x-mastory-api-key: ${{ inputs.api_key }}" --upload-file "$file"
        done

        echo "Processing deleted files"
        for file in ${{ steps.changes.outputs.deleted_files }}; do
          echo "- deleting $file ..."
          echo -n "  "
          curl -s -X DELETE $URL_BASE/${{ inputs.scope }}/$file -H "x-mastory-api-key: ${{ inputs.api_key }}"
        done

      # echo "Processing renamed files"
      # for file in ${{ steps.changes.outputs.renamed_files }}; do
      #   echo "- $file ..."
      # done
      # echo "Processing copied files"
      # for file in ${{ steps.changes.outputs.copied_files }}; do
      #   echo "- $file ..."
      # done
