name: Mastory Content Action
description: Propagates changes to your repository so they become directly available in Mastory.

inputs:
  scope:
    description: Your content contributor scope (by default, your GitHub user or organization name). Check your profile page on mastory.io if you are unsure what your scope name is.
    required: false
    default: ${{ github.repository_owner }}
  api_key:
    description: Your Mastory API key.
    required: true
  add:
    description: |
      Adds all files in your repository to your content scope, assuming they are not yet present.
    default: ''
  reinit:
    description: |
      Re-initializes your content scope based on a full re-evaluation of your repository.
    default: ''
  url_base:
    description: The base URL for calls to the Content API.
    default: https://app.mastory.io/api/content
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - if: inputs.reinit
      run: |
        echo "Reinitializing your scope to the state of this repository."
        ${GITHUB_ACTION_PATH}/clear-scope.sh
      shell: bash
      env:
        url: ${{ inputs.url_base }}
        scope: ${{ inputs.scope }}
        api_key: ${{ inputs.api_key }}
    - if: inputs.reinit || inputs.add
      run: ${GITHUB_ACTION_PATH}/add-all-files.sh
      shell: bash
      env:
        url: ${{ inputs.url_base }}
        scope: ${{ inputs.scope }}
        api_key: ${{ inputs.api_key }}
    - if: '!(inputs.reinit || inputs.add)'
      id: changes
      uses: tj-actions/changed-files@v45
      with:
        separator: '<'
        quotepath: 'false'
        safe_output: 'false'
        include_all_old_new_renamed_files: 'true'
        old_new_files_separator: '>'
        old_new_separator: '>'
        files_ignore: |
          .*
          .*/**
    - if: '!(inputs.reinit || inputs.add)'
      run: ${GITHUB_ACTION_PATH}/process-changes.sh
      shell: bash
      env:
        a: ${{ steps.changes.outputs.added_files }}
        m: ${{ steps.changes.outputs.modified_files }}
        d: ${{ steps.changes.outputs.deleted_files }}
        r: ${{ steps.changes.outputs.all_old_new_renamed_files }}
        c: ${{ steps.changes.outputs.copied_files }}
        url: ${{ inputs.url_base }}
        scope: ${{ inputs.scope }}
        api_key: ${{ inputs.api_key }}